spring:
  application:
    name: football-manager

  datasource:
    url://localhost:3306/football_db?useSSL=false&allowPublicKeyRetrieval=true
  usernamr: root
  password: @Acctonvn12345"

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  server:
    prot: 8080

