spring:
  application:
    name: football-manager

  datasource:
    url: jdbc:mysql://localhost:3306/football_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "@Acctonvn12345"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

upload:
  dir: "D:/uploads/football"

server:
  port: 8080
